#!/usr/bin/env python
import sys
import getopt
from ROOT import gROOT, gStyle, TFile, TTree, TChain, TMVA, TCut, TCanvas, gDirectory, TH1, TGraph, gPad, TF1

def print_usage():
    print "\nUsage: {0} <output file basename> <recon A' ROOT file> <slic A' ROOT file".format(sys.argv[0])
    print "Arguments: "
    print '\t-e: use this beam energy'
    print '\t-h: this help message'
    print

ebeam=1.056
mass=0.030

options, remainder = getopt.gnu_getopt(sys.argv[1:], 'e:h')

# Parse the command line arguments
for opt, arg in options:
        if opt=='-e':
            ebeam=float(arg)
        if opt=='-h':
            print_usage()
            sys.exit(0)

if len(remainder)!=3:
    print_usage()
    sys.exit(0)

gROOT.SetBatch(True)
gStyle.SetOptFit(1)
inFile = TFile(remainder[1])
inFile2 = TFile(remainder[2])
#outFile = TFile(remainder[0]+".root","RECREATE")
events = inFile.Get("cut")
events2 = inFile2.Get("ntuple")

c = TCanvas("c","c",1200,900);
c.Print(remainder[0]+".pdf[")
outfile = TFile(remainder[0]+".root","RECREATE")

#exppol3=TF1("exppol3","exp(pol3(0))",-5,100)
exppol4=TF1("exppol4","exp(pol4(0))",-5,100)
#exppol4.SetParameters(-5,0,-0.001,0)

c.Clear()
c.Divide(1,2)
c.cd(1)
gPad.SetLogy(1)
events2.Draw("triEndZ>>prodZ(50,-5,100)","triP>0.8*1.056","colz,goff")
prodZ = gDirectory.Get("prodZ")
prodZ.Fit("expo","L")
prodZ.Draw()
prodZ.Write("prodz")
c.cd(2)
events2.Draw("triP>>hnew(100,0,1.5)","","colz,goff")
hnew = gDirectory.Get("hnew")
hnew.Draw()
hnew.Write("esum")
c.Print(remainder[0]+".pdf","Title:top_yz")


c.Clear()
c.Divide(1,2)
c.cd(1)
#gPad.SetLogy(1)
events.Draw("triEndZ>>hnew(50,-5,100)","triP>0.8*1.056&&uncP>0.8*1.056","colz,goff")
hnew = gDirectory.Get("hnew")
hnew.Draw()
c.cd(2)
eff=hnew.Clone("eff")
eff.Sumw2()
eff.Divide(prodZ)
eff.Draw()
eff.Fit("exppol4","QLN")
eff.Fit("exppol4","IM")
effAtZero=exppol4.Eval(-5)
eff.GetYaxis().SetRangeUser(0,1.2*effAtZero)
eff.Write("eff_all")
c.Print(remainder[0]+".pdf","Title:top_yz")

c.Clear()
c.Divide(1,2)
c.cd(1)
#gPad.SetLogy(1)
events.Draw("triEndZ>>hnew(50,-5,100)","triP>0.8*1.056&&uncP>0.8*1.056&&eleHasL1&&posHasL1","colz,goff")
hnew = gDirectory.Get("hnew")
hnew.Draw()
c.cd(2)
eff=hnew.Clone("eff")
eff.Sumw2()
eff.Divide(prodZ)
eff.Scale(1.0/effAtZero)
eff.Draw()
eff.Fit("exppol4","QLN")
eff.Fit("exppol4","IM")
eff.GetYaxis().SetRangeUser(0,1.2)
eff.Write("eff_L1")
c.Print(remainder[0]+".pdf","Title:top_yz")

c.Clear()
c.Divide(1,2)
c.cd(1)
#gPad.SetLogy(1)
events.Draw("triEndZ>>hnew(50,-5,100)","triP>0.8*1.056&&uncP>0.8*1.056&&!eleHasL1&&posHasL1","colz,goff")
hnew = gDirectory.Get("hnew")
hnew.Draw()
c.cd(2)
eff=hnew.Clone("eff")
eff.Sumw2()
eff.Divide(prodZ)
eff.Scale(1.0/effAtZero)
eff.Draw()
eff.Fit("exppol4","QLN")
eff.Fit("exppol4","IM")
eff.GetYaxis().SetRangeUser(0,1.2)
eff.Write("eff_posL1")
c.Print(remainder[0]+".pdf","Title:top_yz")

c.Clear()
c.Divide(1,2)
c.cd(1)
#gPad.SetLogy(1)
events.Draw("triEndZ>>hnew(50,-5,100)","triP>0.8*1.056&&uncP>0.8*1.056&&eleHasL1&&!posHasL1","colz,goff")
hnew = gDirectory.Get("hnew")
hnew.Draw()
c.cd(2)
eff=hnew.Clone("eff")
eff.Sumw2()
eff.Divide(prodZ)
eff.Scale(1.0/effAtZero)
eff.Draw()
eff.Fit("exppol4","QLN")
eff.Fit("exppol4","IM")
eff.GetYaxis().SetRangeUser(0,1.2)
eff.Write("eff_eleL1")
c.Print(remainder[0]+".pdf","Title:top_yz")

c.Clear()
c.Divide(1,2)
c.cd(1)
#gPad.SetLogy(1)
events.Draw("triEndZ>>hnew(50,-5,100)","triP>0.8*1.056&&uncP>0.8*1.056&&!eleHasL1&&!posHasL1","colz,goff")
hnew = gDirectory.Get("hnew")
hnew.Draw()
c.cd(2)
eff=hnew.Clone("eff")
eff.Sumw2()
eff.Divide(prodZ)
eff.Scale(1.0/effAtZero)
eff.Draw()
eff.Fit("exppol4","QLN")
eff.Fit("exppol4","IM")
eff.GetYaxis().SetRangeUser(0,1.2)
eff.Write("eff_noL1")
c.Print(remainder[0]+".pdf","Title:top_yz")

c.Clear()
c.Divide(1,2)
c.cd(1)
gPad.SetLogz(1)
events.Draw("uncVZ-triEndZ:triEndZ>>hnew(50,-5,100,50,-20,20)","triP>0.8*1.056&&uncP>0.8*1.056","colz")
hnew = gDirectory.Get("hnew")
hnew.FitSlicesY()
hnew_1 = gDirectory.Get("hnew_2")
c.cd(2)
hnew_1.Draw()
hnew_1.Fit("pol2","","",-5,100)
hnew_1.GetYaxis().SetRangeUser(0,20)
hnew_1.Write("zres_all")
c.Print(remainder[0]+".pdf","Title:top_yz")

c.Clear()
c.Divide(1,2)
c.cd(1)
gPad.SetLogz(1)
events.Draw("uncVZ-triEndZ:triEndZ>>hnew(50,-5,100,50,-20,20)","triP>0.8*1.056&&uncP>0.8*1.056&&eleHasL1&&posHasL1","colz")
hnew = gDirectory.Get("hnew")
hnew.FitSlicesY()
hnew_1 = gDirectory.Get("hnew_2")
c.cd(2)
hnew_1.Draw()
hnew_1.Fit("pol1","","",-5,100)
hnew_1.GetYaxis().SetRangeUser(0,20)
hnew_1.Write("zres_L1")
c.Print(remainder[0]+".pdf","Title:top_yz")

c.Clear()
c.Divide(1,2)
c.cd(1)
gPad.SetLogz(1)
events.Draw("uncVZ-triEndZ:triEndZ>>hnew(50,-5,100,50,-20,20)","triP>0.8*1.056&&uncP>0.8*1.056&&!eleHasL1&&posHasL1","colz")
hnew = gDirectory.Get("hnew")
hnew.FitSlicesY()
hnew_1 = gDirectory.Get("hnew_2")
c.cd(2)
hnew_1.Draw()
hnew_1.Fit("pol1","","",-5,100)
hnew_1.GetYaxis().SetRangeUser(0,20)
hnew_1.Write("zres_posL1")
c.Print(remainder[0]+".pdf","Title:top_yz")

c.Clear()
c.Divide(1,2)
c.cd(1)
gPad.SetLogz(1)
events.Draw("uncVZ-triEndZ:triEndZ>>hnew(50,-5,100,50,-20,20)","triP>0.8*1.056&&uncP>0.8*1.056&&eleHasL1&&!posHasL1","colz")
hnew = gDirectory.Get("hnew")
hnew.FitSlicesY()
hnew_1 = gDirectory.Get("hnew_2")
c.cd(2)
hnew_1.Draw()
hnew_1.Fit("pol1","","",-5,100)
hnew_1.GetYaxis().SetRangeUser(0,20)
hnew_1.Write("zres_eleL1")
c.Print(remainder[0]+".pdf","Title:top_yz")

c.Clear()
c.Divide(1,2)
c.cd(1)
gPad.SetLogz(1)
events.Draw("uncVZ-triEndZ:triEndZ>>hnew(50,-5,100,50,-20,20)","triP>0.8*1.056&&uncP>0.8*1.056&&!eleHasL1&&!posHasL1","colz")
hnew = gDirectory.Get("hnew")
hnew.FitSlicesY()
hnew_1 = gDirectory.Get("hnew_2")
c.cd(2)
hnew_1.Draw()
hnew_1.Fit("pol1","","",-5,100)
hnew_1.GetYaxis().SetRangeUser(0,20)
hnew_1.Write("zres_noL1")
c.Print(remainder[0]+".pdf","Title:top_yz")

c.Clear()
c.Divide(1,2)
c.cd(1)
gPad.SetLogz(1)
events.Draw("uncM-triM:triEndZ>>hnew(50,-5,100,50,-0.02,0.02)","triP>0.8*1.056&&uncP>0.8*1.056","colz")
hnew = gDirectory.Get("hnew")
hnew.FitSlicesY()
hnew_1 = gDirectory.Get("hnew_2")
c.cd(2)
hnew_1.Draw()
hnew_1.Fit("pol1","","",-5,100)
hnew_1.GetYaxis().SetRangeUser(0,0.01)
hnew_1.Write("mres_all")
c.Print(remainder[0]+".pdf","Title:top_yz")

c.Clear()
c.Divide(1,2)
c.cd(1)
gPad.SetLogz(1)
events.Draw("uncM-triM:triEndZ>>hnew(50,-5,100,50,-0.02,0.02)","triP>0.8*1.056&&uncP>0.8*1.056&&eleHasL1&&posHasL1","colz")
hnew = gDirectory.Get("hnew")
hnew.FitSlicesY()
hnew_1 = gDirectory.Get("hnew_2")
c.cd(2)
hnew_1.Draw()
hnew_1.Fit("pol1","","",-5,100)
hnew_1.GetYaxis().SetRangeUser(0,0.01)
hnew_1.Write("mres_L1")
c.Print(remainder[0]+".pdf","Title:top_yz")

c.Clear()
c.Divide(1,2)
c.cd(1)
gPad.SetLogz(1)
events.Draw("uncM-triM:triEndZ>>hnew(50,-5,100,50,-0.02,0.02)","triP>0.8*1.056&&uncP>0.8*1.056&&!eleHasL1&&posHasL1","colz")
hnew = gDirectory.Get("hnew")
hnew.FitSlicesY()
hnew_1 = gDirectory.Get("hnew_2")
c.cd(2)
hnew_1.Draw()
hnew_1.Fit("pol1","","",-5,100)
hnew_1.GetYaxis().SetRangeUser(0,0.01)
hnew_1.Write("mres_posL1")
c.Print(remainder[0]+".pdf","Title:top_yz")

c.Clear()
c.Divide(1,2)
c.cd(1)
gPad.SetLogz(1)
events.Draw("uncM-triM:triEndZ>>hnew(50,-5,100,50,-0.02,0.02)","triP>0.8*1.056&&uncP>0.8*1.056&&eleHasL1&&!posHasL1","colz")
hnew = gDirectory.Get("hnew")
hnew.FitSlicesY()
hnew_1 = gDirectory.Get("hnew_2")
c.cd(2)
hnew_1.Draw()
hnew_1.Fit("pol1","","",-5,100)
hnew_1.GetYaxis().SetRangeUser(0,0.01)
hnew_1.Write("mres_eleL1")
c.Print(remainder[0]+".pdf","Title:top_yz")

c.Clear()
c.Divide(1,2)
c.cd(1)
gPad.SetLogz(1)
events.Draw("uncM-triM:triEndZ>>hnew(50,-5,100,50,-0.02,0.02)","triP>0.8*1.056&&uncP>0.8*1.056&&!eleHasL1&&!posHasL1","colz")
hnew = gDirectory.Get("hnew")
hnew.FitSlicesY()
hnew_1 = gDirectory.Get("hnew_2")
c.cd(2)
hnew_1.Draw()
hnew_1.Fit("pol1","","",-5,100)
hnew_1.GetYaxis().SetRangeUser(0,0.01)
hnew_1.Write("mres_noL1")
c.Print(remainder[0]+".pdf","Title:top_yz")

c.Print(remainder[0]+".pdf]")

#events.Draw("fspP+0.25*(fspPX/fspP-0.02)+1.25*abs(fspPX/fspP-0.02)+0.02>>fee_bot(100,{0},{1})".format(0.7*ebeam,1.3*ebeam),"(isSingle0||isSingle1)&&fspTrkHits==6&&fspMatchChisq<3&&fspClE>0.85*{0}&&fspPY/fspP<-0.03".format(ebeam),"colz")
#events.Draw("fspP+0.05*(fspPX/fspP-0.02)-0.05*abs(fspPX/fspP-0.02)+0.02>>fee_top(100,{0},{1})".format(0.7*ebeam,1.3*ebeam),"(isSingle0||isSingle1)&&fspTrkHits==6&&fspMatchChisq<3&&fspClE>0.85*{0}&&fspPY/fspP>0.03".format(ebeam),"colz")
#events.Draw("fspP+0.25*(fspPX/fspP-0.02)+1.25*abs(fspPX/fspP-0.02)+0.02>>fee_single0_bot(100,{0},{1})".format(0.7*ebeam,1.3*ebeam),"(isSingle0)&&fspTrkHits==6&&fspMatchChisq<3&&fspClE>0.85*{0}&&fspPY/fspP<-0.03".format(ebeam),"colz")
#events.Draw("fspP+0.05*(fspPX/fspP-0.02)-0.05*abs(fspPX/fspP-0.02)+0.02>>fee_single0_top(100,{0},{1})".format(0.7*ebeam,1.3*ebeam),"(isSingle0)&&fspTrkHits==6&&fspMatchChisq<3&&fspClE>0.85*{0}&&fspPY/fspP>0.03".format(ebeam),"colz")
outfile.Write()
outfile.Close()

