//
// File generated by /Users/baltzell/Software/root_v5.34.20-cocoa/bin/rootcint at Sun Jan 18 17:09:22 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dictsdIDarwinmIx86_64dIEvioTooldIEvioToolDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "EvioToolDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void EvioTool_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void EvioTool_Dictionary();
   static void *new_EvioTool(void *p = 0);
   static void *newArray_EvioTool(Long_t size, void *p);
   static void delete_EvioTool(void *p);
   static void deleteArray_EvioTool(void *p);
   static void destruct_EvioTool(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::EvioTool*)
   {
      ::EvioTool *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(::EvioTool),0);
      static ::ROOT::TGenericClassInfo 
         instance("EvioTool", "./EvioTool/EvioTool.h", 48,
                  typeid(::EvioTool), DefineBehavior(ptr, ptr),
                  0, &EvioTool_Dictionary, isa_proxy, 1,
                  sizeof(::EvioTool) );
      instance.SetNew(&new_EvioTool);
      instance.SetNewArray(&newArray_EvioTool);
      instance.SetDelete(&delete_EvioTool);
      instance.SetDeleteArray(&deleteArray_EvioTool);
      instance.SetDestructor(&destruct_EvioTool);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::EvioTool*)
   {
      return GenerateInitInstanceLocal((::EvioTool*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::EvioTool*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void EvioTool_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const ::EvioTool*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_EvioTool(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) ::EvioTool : new ::EvioTool;
   }
   static void *newArray_EvioTool(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) ::EvioTool[nElements] : new ::EvioTool[nElements];
   }
   // Wrapper around operator delete
   static void delete_EvioTool(void *p) {
      delete ((::EvioTool*)p);
   }
   static void deleteArray_EvioTool(void *p) {
      delete [] ((::EvioTool*)p);
   }
   static void destruct_EvioTool(void *p) {
      typedef ::EvioTool current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::EvioTool

/********************************************************
* dicts/Darwin-x86_64/EvioTool/EvioToolDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableEvioToolDict();

extern "C" void G__set_cpp_environmentEvioToolDict() {
  G__cpp_reset_tagtableEvioToolDict();
}
#include <new>
extern "C" int G__cpp_dllrevEvioToolDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* EvioTool */
static int G__EvioToolDict_225_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EvioTool* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 2:
     //m: 2
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EvioTool((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
     } else {
       p = new((void*) gvp) EvioTool((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
     }
     break;
   case 1:
     //m: 1
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new EvioTool((const char*) G__int(libp->para[0]));
     } else {
       p = new((void*) gvp) EvioTool((const char*) G__int(libp->para[0]));
     }
     break;
   case 0:
     int n = G__getaryconstruct();
     if (n) {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new EvioTool[n];
       } else {
         p = new((void*) gvp) EvioTool[n];
       }
     } else {
       if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
         p = new EvioTool;
       } else {
         p = new((void*) gvp) EvioTool;
       }
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EvioToolDictLN_EvioTool));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvioToolDict_225_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EvioTool*) G__getstructoffset())->init();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvioToolDict_225_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 72, (long) ((EvioTool*) G__getstructoffset())->getBuffer());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvioToolDict_225_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EvioTool*) G__getstructoffset())->getBufSize());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvioToolDict_225_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      ((EvioTool*) G__getstructoffset())->open((const char*) G__int(libp->para[0]), (const char*) G__int(libp->para[1]));
      G__setnull(result7);
      break;
   case 1:
      ((EvioTool*) G__getstructoffset())->open((const char*) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvioToolDict_225_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EvioTool*) G__getstructoffset())->openEv((char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvioToolDict_225_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((EvioTool*) G__getstructoffset())->ReadNoCopy((int) G__int(libp->para[0]), (const unsigned int**) G__int(libp->para[1])
, (unsigned int*) G__int(libp->para[2])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvioToolDict_225_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 3:
      G__letint(result7, 105, (long) ((EvioTool*) G__getstructoffset())->openEt((const char*) G__int(libp->para[0]), (int) G__int(libp->para[1])
, (int) G__int(libp->para[2])));
      break;
   case 2:
      G__letint(result7, 105, (long) ((EvioTool*) G__getstructoffset())->openEt((const char*) G__int(libp->para[0]), (int) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 105, (long) ((EvioTool*) G__getstructoffset())->openEt((const char*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 105, (long) ((EvioTool*) G__getstructoffset())->openEt());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvioToolDict_225_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 105, (long) ((EvioTool*) G__getstructoffset())->parse((EVIO_Event_t*) G__int(libp->para[0]), (const unsigned int*) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 105, (long) ((EvioTool*) G__getstructoffset())->parse((EVIO_Event_t*) G__int(libp->para[0])));
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvioToolDict_225_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EvioTool*) G__getstructoffset())->parseDictionary((const char*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvioToolDict_225_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((EvioTool*) G__getstructoffset())->printDictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__EvioToolDict_225_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 103, (long) ((EvioTool*) G__getstructoffset())->read());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__EvioToolDict_225_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   EvioTool* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new EvioTool(*(EvioTool*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__EvioToolDictLN_EvioTool));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef EvioTool G__TEvioTool;
static int G__EvioToolDict_225_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (EvioTool*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((EvioTool*) (soff+(sizeof(EvioTool)*i)))->~G__TEvioTool();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (EvioTool*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((EvioTool*) (soff))->~G__TEvioTool();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__EvioToolDict_225_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   EvioTool* dest = (EvioTool*) G__getstructoffset();
   *dest = *(EvioTool*) libp->para[0].ref;
   const EvioTool& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* EvioTool */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncEvioToolDict {
 public:
  G__Sizep2memfuncEvioToolDict(): p(&G__Sizep2memfuncEvioToolDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncEvioToolDict::*p)();
};

size_t G__get_sizep2memfuncEvioToolDict()
{
  G__Sizep2memfuncEvioToolDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceEvioToolDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableEvioToolDict() {

   /* Setting up typedef entry */
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<int>",117,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEintcOallocatorlEintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEintcOallocatorlEintgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<FADC_chan_f13_t>",117,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_chan_f13_tcOallocatorlEFADC_chan_f13_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f13_tcOallocatorlEFADC_chan_f13_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_chan_f13_tcOallocatorlEFADC_chan_f13_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f13_tcOallocatorlEFADC_chan_f13_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_chan_f13_tcOallocatorlEFADC_chan_f13_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<FADC_chan_f15_t>",117,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_chan_f15_tcOallocatorlEFADC_chan_f15_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f15_tcOallocatorlEFADC_chan_f15_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_chan_f15_tcOallocatorlEFADC_chan_f15_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f15_tcOallocatorlEFADC_chan_f15_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_chan_f15_tcOallocatorlEFADC_chan_f15_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<FADC_chan_f21_t>",117,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_chan_f21_tcOallocatorlEFADC_chan_f21_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f21_tcOallocatorlEFADC_chan_f21_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_chan_f21_tcOallocatorlEFADC_chan_f21_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f21_tcOallocatorlEFADC_chan_f21_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_chan_f21_tcOallocatorlEFADC_chan_f21_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SSP_cluster_t>",117,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlESSP_cluster_tcOallocatorlESSP_cluster_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_cluster_tcOallocatorlESSP_cluster_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlESSP_cluster_tcOallocatorlESSP_cluster_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_cluster_tcOallocatorlESSP_cluster_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlESSP_cluster_tcOallocatorlESSP_cluster_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SSP_single_t>",117,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlESSP_single_tcOallocatorlESSP_single_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_single_tcOallocatorlESSP_single_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlESSP_single_tcOallocatorlESSP_single_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_single_tcOallocatorlESSP_single_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlESSP_single_tcOallocatorlESSP_single_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SSP_pair_t>",117,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlESSP_pair_tcOallocatorlESSP_pair_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_pair_tcOallocatorlESSP_pair_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlESSP_pair_tcOallocatorlESSP_pair_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_pair_tcOallocatorlESSP_pair_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlESSP_pair_tcOallocatorlESSP_pair_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<FADC_data_f13_t>",117,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_data_f13_tcOallocatorlEFADC_data_f13_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f13_tcOallocatorlEFADC_data_f13_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_data_f13_tcOallocatorlEFADC_data_f13_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f13_tcOallocatorlEFADC_data_f13_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_data_f13_tcOallocatorlEFADC_data_f13_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<FADC_data_f15_t>",117,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_data_f15_tcOallocatorlEFADC_data_f15_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f15_tcOallocatorlEFADC_data_f15_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_data_f15_tcOallocatorlEFADC_data_f15_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f15_tcOallocatorlEFADC_data_f15_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_data_f15_tcOallocatorlEFADC_data_f15_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<FADC_data_f21_t>",117,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_data_f21_tcOallocatorlEFADC_data_f21_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f21_tcOallocatorlEFADC_data_f21_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_data_f21_tcOallocatorlEFADC_data_f21_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f21_tcOallocatorlEFADC_data_f21_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlEFADC_data_f21_tcOallocatorlEFADC_data_f21_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<SVT_chan_t>",117,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlESVT_chan_tcOallocatorlESVT_chan_tgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlESVT_chan_tcOallocatorlESVT_chan_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlESVT_chan_tcOallocatorlESVT_chan_tgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__EvioToolDictLN_reverse_iteratorlEvectorlESVT_chan_tcOallocatorlESVT_chan_tgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__EvioToolDictLN_vectorlESVT_chan_tcOallocatorlESVT_chan_tgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* EvioTool */
static void G__setup_memvarEvioTool(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__EvioToolDictLN_EvioTool));
   { EvioTool *p; p=(EvioTool*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fDebug)-(long)(p)),105,0,0,-1,-1,-1,1,"fDebug=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->MaxBuff)-(long)(p)),105,0,0,-1,-1,-1,1,"MaxBuff=",0,"Size of the evioFileChannel buffer. Must contain entire event.");
   G__memvar_setup((void*)((long)(&p->run_number)-(long)(p)),105,0,0,-1,-1,-1,1,"run_number=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->start_time)-(long)(p)),105,0,0,-1,-1,-1,1,"start_time=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->file_number)-(long)(p)),105,0,0,-1,-1,-1,1,"file_number=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->et_station_name)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__EvioToolDictLN_string),-1,-1,1,"et_station_name=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->et_host_name)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__EvioToolDictLN_string),-1,-1,1,"et_host_name=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->et_port)-(long)(p)),105,0,0,-1,-1,-1,1,"et_port=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->et_file_name)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__EvioToolDictLN_string),-1,-1,1,"et_file_name=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->et_is_blocking)-(long)(p)),103,0,0,-1,-1,-1,1,"et_is_blocking=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->et_mode)-(long)(p)),105,0,0,-1,-1,-1,1,"et_mode=",0,"ET_HOST_AS_LOCAL(1) or ET_HOST_AS_REMOTE(0) - set the mode behavior.");
   G__memvar_setup((void*)((long)(&p->et_que_size)-(long)(p)),105,0,0,-1,-1,-1,1,"et_que_size=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->et_pre_scale)-(long)(p)),105,0,0,-1,-1,-1,1,"et_pre_scale=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->et_receive_buffer_size)-(long)(p)),105,0,0,-1,-1,-1,1,"et_receive_buffer_size=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->et_send_buffer_size)-(long)(p)),105,0,0,-1,-1,-1,1,"et_send_buffer_size=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->et_nodelay)-(long)(p)),105,0,0,-1,-1,-1,1,"et_nodelay=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->et_events_chunk)-(long)(p)),105,0,0,-1,-1,-1,1,"et_events_chunk=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->et_data)-(long)(p)),72,0,0,-1,-1,-1,1,"et_data=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->et_data_len)-(long)(p)),107,0,0,-1,G__defined_typename("size_t"),-1,1,"et_data_len=",0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("EVENT_PRESTART=%lldLL",(long long)EvioTool::EVENT_PRESTART).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("EVENT_GO=%lldLL",(long long)EvioTool::EVENT_GO).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("ECAL_FADC_MASTER=%lldLL",(long long)EvioTool::ECAL_FADC_MASTER).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("ECAL_FADC_CRATE1=%lldLL",(long long)EvioTool::ECAL_FADC_CRATE1).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("ECAL_FADC_CRATE2=%lldLL",(long long)EvioTool::ECAL_FADC_CRATE2).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("ECAL_FADC_GTP1=%lldLL",(long long)EvioTool::ECAL_FADC_GTP1).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("ECAL_FADC_GTP2=%lldLL",(long long)EvioTool::ECAL_FADC_GTP2).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("EVENT_HEADER=%lldLL",(long long)EvioTool::EVENT_HEADER).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("ECAL_INTEGRAL_MODE=%lldLL",(long long)EvioTool::ECAL_INTEGRAL_MODE).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("ECAL_HIGHRES_MODE=%lldLL",(long long)EvioTool::ECAL_HIGHRES_MODE).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("ECAL_RAW_MODE=%lldLL",(long long)EvioTool::ECAL_RAW_MODE).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("TRIGGER_BANK_OLD=%lldLL",(long long)EvioTool::TRIGGER_BANK_OLD).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("SSP_BANK=%lldLL",(long long)EvioTool::SSP_BANK).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("TRIGGER_BANK=%lldLL",(long long)EvioTool::TRIGGER_BANK).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("SVT_CRATE_3=%lldLL",(long long)EvioTool::SVT_CRATE_3).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("DAQCONFIG_BANK=%lldLL",(long long)EvioTool::DAQCONFIG_BANK).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("COSMIC_CRATE=%lldLL",(long long)EvioTool::COSMIC_CRATE).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("COSMIC_SLOT=%lldLL",(long long)EvioTool::COSMIC_SLOT).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("N_FADC_SLOTS=%lldLL",(long long)EvioTool::N_FADC_SLOTS).data(),0,(char*)NULL);
   G__memvar_setup((void*)G__PVOID,105,0,1,-1,-1,-2,1,G__FastAllocString(2048).Format("N_FADC_CHANS=%lldLL",(long long)EvioTool::N_FADC_CHANS).data(),0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->fIgnoreFADC)-(long)(p)),103,0,0,-1,-1,-1,1,"fIgnoreFADC=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"get_events_from_et=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"et_events_need_put=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"et_num_read=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"et_events_remaining=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarEvioToolDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncEvioTool(void) {
   /* EvioTool */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__EvioToolDictLN_EvioTool));
   G__memfunc_setup("EvioTool",817,G__EvioToolDict_225_0_1, 105, G__get_linked_tagnum(&G__EvioToolDictLN_EvioTool), -1, 0, 2, 1, 1, 0, 
"C - - 10 '0' filename C - - 10 '0' dict_filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("init",436,G__EvioToolDict_225_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getBuffer",922,G__EvioToolDict_225_0_3, 72, -1, -1, 0, 0, 1, 1, 1, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getBufSize",1016,G__EvioToolDict_225_0_4, 105, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("open",434,G__EvioToolDict_225_0_5, 121, -1, -1, 0, 2, 1, 1, 0, 
"C - - 10 - filename C - - 10 '0' dict_filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("openEv",621,G__EvioToolDict_225_0_6, 105, -1, -1, 0, 1, 1, 1, 0, "C - - 0 - filename", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("ReadNoCopy",980,G__EvioToolDict_225_0_7, 105, -1, -1, 0, 3, 1, 1, 0, 
"i - - 0 - handle H - - 12 - buffer "
"H - - 0 - buflen", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("openEt",619,G__EvioToolDict_225_0_8, 105, -1, -1, 0, 3, 1, 1, 0, 
"C - - 10 '\"\"' et_file_name i - - 0 '0' port "
"i - - 0 '1' prescale", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("parse",539,G__EvioToolDict_225_0_9, 105, -1, -1, 0, 2, 1, 1, 0, 
"U 'EVIO_Event_t' - 0 - evt H - - 10 '0' buff", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("parseDictionary",1585,G__EvioToolDict_225_0_10, 121, -1, -1, 0, 1, 1, 1, 0, "C - - 10 - dictf", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("printDictionary",1603,G__EvioToolDict_225_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("read",412,G__EvioToolDict_225_0_12, 103, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   // automatic copy constructor
   G__memfunc_setup("EvioTool", 817, G__EvioToolDict_225_0_13, (int) ('i'), G__get_linked_tagnum(&G__EvioToolDictLN_EvioTool), -1, 0, 1, 1, 1, 0, "u 'EvioTool' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~EvioTool", 943, G__EvioToolDict_225_0_14, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__EvioToolDict_225_0_15, (int) ('u'), G__get_linked_tagnum(&G__EvioToolDictLN_EvioTool), -1, 1, 1, 1, 1, 0, "u 'EvioTool' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncEvioToolDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalEvioToolDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcEvioToolDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__EvioToolDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_vectorlEintcOallocatorlEintgRsPgR = { "vector<int,allocator<int> >" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<int,allocator<int> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_vectorlEFADC_chan_f13_tcOallocatorlEFADC_chan_f13_tgRsPgR = { "vector<FADC_chan_f13_t,allocator<FADC_chan_f13_t> >" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f13_tcOallocatorlEFADC_chan_f13_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<FADC_chan_f13_t,allocator<FADC_chan_f13_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_vectorlEFADC_chan_f15_tcOallocatorlEFADC_chan_f15_tgRsPgR = { "vector<FADC_chan_f15_t,allocator<FADC_chan_f15_t> >" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f15_tcOallocatorlEFADC_chan_f15_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<FADC_chan_f15_t,allocator<FADC_chan_f15_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_vectorlEFADC_chan_f21_tcOallocatorlEFADC_chan_f21_tgRsPgR = { "vector<FADC_chan_f21_t,allocator<FADC_chan_f21_t> >" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f21_tcOallocatorlEFADC_chan_f21_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<FADC_chan_f21_t,allocator<FADC_chan_f21_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_vectorlESSP_cluster_tcOallocatorlESSP_cluster_tgRsPgR = { "vector<SSP_cluster_t,allocator<SSP_cluster_t> >" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_cluster_tcOallocatorlESSP_cluster_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SSP_cluster_t,allocator<SSP_cluster_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_vectorlESSP_single_tcOallocatorlESSP_single_tgRsPgR = { "vector<SSP_single_t,allocator<SSP_single_t> >" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_single_tcOallocatorlESSP_single_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SSP_single_t,allocator<SSP_single_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_vectorlESSP_pair_tcOallocatorlESSP_pair_tgRsPgR = { "vector<SSP_pair_t,allocator<SSP_pair_t> >" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_pair_tcOallocatorlESSP_pair_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SSP_pair_t,allocator<SSP_pair_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_EVIO_Event_t = { "EVIO_Event_t" , 115 , -1 };
G__linked_taginfo G__EvioToolDictLN_vectorlEFADC_data_f13_tcOallocatorlEFADC_data_f13_tgRsPgR = { "vector<FADC_data_f13_t,allocator<FADC_data_f13_t> >" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f13_tcOallocatorlEFADC_data_f13_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<FADC_data_f13_t,allocator<FADC_data_f13_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_vectorlEFADC_data_f15_tcOallocatorlEFADC_data_f15_tgRsPgR = { "vector<FADC_data_f15_t,allocator<FADC_data_f15_t> >" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f15_tcOallocatorlEFADC_data_f15_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<FADC_data_f15_t,allocator<FADC_data_f15_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_vectorlEFADC_data_f21_tcOallocatorlEFADC_data_f21_tgRsPgR = { "vector<FADC_data_f21_t,allocator<FADC_data_f21_t> >" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f21_tcOallocatorlEFADC_data_f21_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<FADC_data_f21_t,allocator<FADC_data_f21_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_vectorlESVT_chan_tcOallocatorlESVT_chan_tgRsPgR = { "vector<SVT_chan_t,allocator<SVT_chan_t> >" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlESVT_chan_tcOallocatorlESVT_chan_tgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<SVT_chan_t,allocator<SVT_chan_t> >::iterator>" , 99 , -1 };
G__linked_taginfo G__EvioToolDictLN_EvioTool = { "EvioTool" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableEvioToolDict() {
  G__EvioToolDictLN_string.tagnum = -1 ;
  G__EvioToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__EvioToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvioToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__EvioToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvioToolDictLN_vectorlEintcOallocatorlEintgRsPgR.tagnum = -1 ;
  G__EvioToolDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvioToolDictLN_vectorlEFADC_chan_f13_tcOallocatorlEFADC_chan_f13_tgRsPgR.tagnum = -1 ;
  G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f13_tcOallocatorlEFADC_chan_f13_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvioToolDictLN_vectorlEFADC_chan_f15_tcOallocatorlEFADC_chan_f15_tgRsPgR.tagnum = -1 ;
  G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f15_tcOallocatorlEFADC_chan_f15_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvioToolDictLN_vectorlEFADC_chan_f21_tcOallocatorlEFADC_chan_f21_tgRsPgR.tagnum = -1 ;
  G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f21_tcOallocatorlEFADC_chan_f21_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvioToolDictLN_vectorlESSP_cluster_tcOallocatorlESSP_cluster_tgRsPgR.tagnum = -1 ;
  G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_cluster_tcOallocatorlESSP_cluster_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvioToolDictLN_vectorlESSP_single_tcOallocatorlESSP_single_tgRsPgR.tagnum = -1 ;
  G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_single_tcOallocatorlESSP_single_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvioToolDictLN_vectorlESSP_pair_tcOallocatorlESSP_pair_tgRsPgR.tagnum = -1 ;
  G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_pair_tcOallocatorlESSP_pair_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvioToolDictLN_EVIO_Event_t.tagnum = -1 ;
  G__EvioToolDictLN_vectorlEFADC_data_f13_tcOallocatorlEFADC_data_f13_tgRsPgR.tagnum = -1 ;
  G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f13_tcOallocatorlEFADC_data_f13_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvioToolDictLN_vectorlEFADC_data_f15_tcOallocatorlEFADC_data_f15_tgRsPgR.tagnum = -1 ;
  G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f15_tcOallocatorlEFADC_data_f15_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvioToolDictLN_vectorlEFADC_data_f21_tcOallocatorlEFADC_data_f21_tgRsPgR.tagnum = -1 ;
  G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f21_tcOallocatorlEFADC_data_f21_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvioToolDictLN_vectorlESVT_chan_tcOallocatorlESVT_chan_tgRsPgR.tagnum = -1 ;
  G__EvioToolDictLN_reverse_iteratorlEvectorlESVT_chan_tcOallocatorlESVT_chan_tgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__EvioToolDictLN_EvioTool.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableEvioToolDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_string);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_vectorlEintcOallocatorlEintgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_vectorlEFADC_chan_f13_tcOallocatorlEFADC_chan_f13_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f13_tcOallocatorlEFADC_chan_f13_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_vectorlEFADC_chan_f15_tcOallocatorlEFADC_chan_f15_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f15_tcOallocatorlEFADC_chan_f15_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_vectorlEFADC_chan_f21_tcOallocatorlEFADC_chan_f21_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f21_tcOallocatorlEFADC_chan_f21_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_vectorlESSP_cluster_tcOallocatorlESSP_cluster_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_cluster_tcOallocatorlESSP_cluster_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_vectorlESSP_single_tcOallocatorlESSP_single_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_single_tcOallocatorlESSP_single_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_vectorlESSP_pair_tcOallocatorlESSP_pair_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_pair_tcOallocatorlESSP_pair_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_EVIO_Event_t);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_vectorlEFADC_data_f13_tcOallocatorlEFADC_data_f13_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f13_tcOallocatorlEFADC_data_f13_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_vectorlEFADC_data_f15_tcOallocatorlEFADC_data_f15_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f15_tcOallocatorlEFADC_data_f15_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_vectorlEFADC_data_f21_tcOallocatorlEFADC_data_f21_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f21_tcOallocatorlEFADC_data_f21_tgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_vectorlESVT_chan_tcOallocatorlESVT_chan_tgRsPgR);
   G__get_linked_tagnum_fwd(&G__EvioToolDictLN_reverse_iteratorlEvectorlESVT_chan_tcOallocatorlESVT_chan_tgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__EvioToolDictLN_EvioTool),sizeof(EvioTool),-1,66816,(char*)NULL,G__setup_memvarEvioTool,G__setup_memfuncEvioTool);
}
extern "C" void G__cpp_setupEvioToolDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupEvioToolDict()");
  G__set_cpp_environmentEvioToolDict();
  G__cpp_setup_tagtableEvioToolDict();

  G__cpp_setup_inheritanceEvioToolDict();

  G__cpp_setup_typetableEvioToolDict();

  G__cpp_setup_memvarEvioToolDict();

  G__cpp_setup_memfuncEvioToolDict();
  G__cpp_setup_globalEvioToolDict();
  G__cpp_setup_funcEvioToolDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncEvioToolDict();
  return;
}
class G__cpp_setup_initEvioToolDict {
  public:
    G__cpp_setup_initEvioToolDict() { G__add_setup_func("EvioToolDict",(G__incsetup)(&G__cpp_setupEvioToolDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initEvioToolDict() { G__remove_setup_func("EvioToolDict"); }
};
G__cpp_setup_initEvioToolDict G__cpp_setup_initializerEvioToolDict;

