/********************************************************************
* dicts/Darwin-x86_64/EvioTool/EvioToolDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Darwin-x86_64/EvioTool/EvioToolDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableEvioToolDict();
extern void G__cpp_setup_inheritanceEvioToolDict();
extern void G__cpp_setup_typetableEvioToolDict();
extern void G__cpp_setup_memvarEvioToolDict();
extern void G__cpp_setup_globalEvioToolDict();
extern void G__cpp_setup_memfuncEvioToolDict();
extern void G__cpp_setup_funcEvioToolDict();
extern void G__set_cpp_environmentEvioToolDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "EvioTool/EvioTool.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__EvioToolDictLN_string;
extern G__linked_taginfo G__EvioToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EvioToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EvioToolDictLN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlEintcOallocatorlEintgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EvioToolDictLN_vectorlEFADC_chan_f13_tcOallocatorlEFADC_chan_f13_tgRsPgR;
extern G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f13_tcOallocatorlEFADC_chan_f13_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EvioToolDictLN_vectorlEFADC_chan_f15_tcOallocatorlEFADC_chan_f15_tgRsPgR;
extern G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f15_tcOallocatorlEFADC_chan_f15_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EvioToolDictLN_vectorlEFADC_chan_f21_tcOallocatorlEFADC_chan_f21_tgRsPgR;
extern G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_chan_f21_tcOallocatorlEFADC_chan_f21_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EvioToolDictLN_vectorlESSP_cluster_tcOallocatorlESSP_cluster_tgRsPgR;
extern G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_cluster_tcOallocatorlESSP_cluster_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EvioToolDictLN_vectorlESSP_single_tcOallocatorlESSP_single_tgRsPgR;
extern G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_single_tcOallocatorlESSP_single_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EvioToolDictLN_vectorlESSP_pair_tcOallocatorlESSP_pair_tgRsPgR;
extern G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlESSP_pair_tcOallocatorlESSP_pair_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EvioToolDictLN_EVIO_Event_t;
extern G__linked_taginfo G__EvioToolDictLN_vectorlEFADC_data_f13_tcOallocatorlEFADC_data_f13_tgRsPgR;
extern G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f13_tcOallocatorlEFADC_data_f13_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EvioToolDictLN_vectorlEFADC_data_f15_tcOallocatorlEFADC_data_f15_tgRsPgR;
extern G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f15_tcOallocatorlEFADC_data_f15_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EvioToolDictLN_vectorlEFADC_data_f21_tcOallocatorlEFADC_data_f21_tgRsPgR;
extern G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlEFADC_data_f21_tcOallocatorlEFADC_data_f21_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EvioToolDictLN_vectorlESVT_chan_tcOallocatorlESVT_chan_tgRsPgR;
extern G__linked_taginfo G__EvioToolDictLN_reverse_iteratorlEvectorlESVT_chan_tcOallocatorlESVT_chan_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__EvioToolDictLN_EvioTool;

/* STUB derived class for protected member access */
