//
// File generated by rootcint at Thu May 21 20:25:27 2015

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME hps_ecal_scalers_Dict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "hps_ecal_scalers_Dict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void hps_ecal_scalers_app_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_hps_ecal_scalers_app(void *p);
   static void deleteArray_hps_ecal_scalers_app(void *p);
   static void destruct_hps_ecal_scalers_app(void *p);
   static void streamer_hps_ecal_scalers_app(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::hps_ecal_scalers_app*)
   {
      ::hps_ecal_scalers_app *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::hps_ecal_scalers_app >(0);
      static ::ROOT::TGenericClassInfo 
         instance("hps_ecal_scalers_app", ::hps_ecal_scalers_app::Class_Version(), "./hps_ecal_scalers.h", 33,
                  typeid(::hps_ecal_scalers_app), DefineBehavior(ptr, ptr),
                  &::hps_ecal_scalers_app::Dictionary, isa_proxy, 0,
                  sizeof(::hps_ecal_scalers_app) );
      instance.SetDelete(&delete_hps_ecal_scalers_app);
      instance.SetDeleteArray(&deleteArray_hps_ecal_scalers_app);
      instance.SetDestructor(&destruct_hps_ecal_scalers_app);
      instance.SetStreamerFunc(&streamer_hps_ecal_scalers_app);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::hps_ecal_scalers_app*)
   {
      return GenerateInitInstanceLocal((::hps_ecal_scalers_app*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::hps_ecal_scalers_app*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
atomic_TClass_ptr hps_ecal_scalers_app::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *hps_ecal_scalers_app::Class_Name()
{
   return "hps_ecal_scalers_app";
}

//______________________________________________________________________________
const char *hps_ecal_scalers_app::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::hps_ecal_scalers_app*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int hps_ecal_scalers_app::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::hps_ecal_scalers_app*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void hps_ecal_scalers_app::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::hps_ecal_scalers_app*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *hps_ecal_scalers_app::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::hps_ecal_scalers_app*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void hps_ecal_scalers_app::Streamer(TBuffer &R__b)
{
   // Stream an object of class hps_ecal_scalers_app.

   TGMainFrame::Streamer(R__b);
}

//______________________________________________________________________________
void hps_ecal_scalers_app::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class hps_ecal_scalers_app.
      TClass *R__cl = ::hps_ecal_scalers_app::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hps_crate_map[2][22]", hps_crate_map);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hps_ecal_crate_slot_scalers[2][22][16]", hps_ecal_crate_slot_scalers);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hps_ecal_crate_slot_ref[2][22]", hps_ecal_crate_slot_ref);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*crate_hps[2]", &crate_hps);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pTC", &pTC);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pH", &pH);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*pCanvas", &pCanvas);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "hpsCrates[2]", hpsCrates);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "doLogScale", &doLogScale);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "updatePeriod", &updatePeriod);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "scalerType", &scalerType);
      TGMainFrame::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_hps_ecal_scalers_app(void *p) {
      delete ((::hps_ecal_scalers_app*)p);
   }
   static void deleteArray_hps_ecal_scalers_app(void *p) {
      delete [] ((::hps_ecal_scalers_app*)p);
   }
   static void destruct_hps_ecal_scalers_app(void *p) {
      typedef ::hps_ecal_scalers_app current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_hps_ecal_scalers_app(TBuffer &buf, void *obj) {
      ((::hps_ecal_scalers_app*)obj)->::hps_ecal_scalers_app::Streamer(buf);
   }
} // end of namespace ROOT for class ::hps_ecal_scalers_app

/********************************************************
* hps_ecal_scalers_Dict.cxx
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtablehps_ecal_scalers_Dict();

extern "C" void G__set_cpp_environmenthps_ecal_scalers_Dict() {
  G__cpp_reset_tagtablehps_ecal_scalers_Dict();
}
#include <new>
extern "C" int G__cpp_dllrevhps_ecal_scalers_Dict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* hps_ecal_scalers_app */
static int G__hps_ecal_scalers_Dict_772_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   hps_ecal_scalers_app* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 3
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new hps_ecal_scalers_app(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   } else {
     p = new((void*) gvp) hps_ecal_scalers_app(
(TGWindow*) G__int(libp->para[0]), (UInt_t) G__int(libp->para[1])
, (UInt_t) G__int(libp->para[2]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_hps_ecal_scalers_app));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hps_ecal_scalers_Dict_772_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((hps_ecal_scalers_app*) G__getstructoffset())->DoExit();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hps_ecal_scalers_Dict_772_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((hps_ecal_scalers_app*) G__getstructoffset())->button_Save();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hps_ecal_scalers_Dict_772_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((hps_ecal_scalers_app*) G__getstructoffset())->button_LogEnable();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hps_ecal_scalers_Dict_772_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((hps_ecal_scalers_app*) G__getstructoffset())->refresh_scalers();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hps_ecal_scalers_Dict_772_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) hps_ecal_scalers_app::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hps_ecal_scalers_Dict_772_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) hps_ecal_scalers_app::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hps_ecal_scalers_Dict_772_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) hps_ecal_scalers_app::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hps_ecal_scalers_Dict_772_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      hps_ecal_scalers_app::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hps_ecal_scalers_Dict_772_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((hps_ecal_scalers_app*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hps_ecal_scalers_Dict_772_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) hps_ecal_scalers_app::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hps_ecal_scalers_Dict_772_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) hps_ecal_scalers_app::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hps_ecal_scalers_Dict_772_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) hps_ecal_scalers_app::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__hps_ecal_scalers_Dict_772_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) hps_ecal_scalers_app::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef hps_ecal_scalers_app G__Thps_ecal_scalers_app;
static int G__hps_ecal_scalers_Dict_772_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (hps_ecal_scalers_app*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((hps_ecal_scalers_app*) (soff+(sizeof(hps_ecal_scalers_app)*i)))->~G__Thps_ecal_scalers_app();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (hps_ecal_scalers_app*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((hps_ecal_scalers_app*) (soff))->~G__Thps_ecal_scalers_app();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* hps_ecal_scalers_app */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfunchps_ecal_scalers_Dict {
 public:
  G__Sizep2memfunchps_ecal_scalers_Dict(): p(&G__Sizep2memfunchps_ecal_scalers_Dict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfunchps_ecal_scalers_Dict::*p)();
};

size_t G__get_sizep2memfunchps_ecal_scalers_Dict()
{
  G__Sizep2memfunchps_ecal_scalers_Dict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritancehps_ecal_scalers_Dict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_hps_ecal_scalers_app))) {
     hps_ecal_scalers_app *G__Lderived;
     G__Lderived=(hps_ecal_scalers_app*)0x1000;
     {
       TGMainFrame *G__Lpbase=(TGMainFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_hps_ecal_scalers_app),G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_TGMainFrame),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TGCompositeFrame *G__Lpbase=(TGCompositeFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_hps_ecal_scalers_app),G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_TGCompositeFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGFrame *G__Lpbase=(TGFrame*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_hps_ecal_scalers_app),G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_TGFrame),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGWindow *G__Lpbase=(TGWindow*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_hps_ecal_scalers_app),G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_TGWindow),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TGObject *G__Lpbase=(TGObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_hps_ecal_scalers_app),G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_TGObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_hps_ecal_scalers_app),G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TQObject *G__Lpbase=(TQObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_hps_ecal_scalers_app),G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_TQObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetablehps_ecal_scalers_Dict() {

   /* Setting up typedef entry */
   G__search_typename2("UInt_t",104,-1,0,-1);
   G__setnewtype(-1,"Unsigned integer 4 bytes (unsigned int)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* hps_ecal_scalers_app */
static void G__setup_memvarhps_ecal_scalers_app(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_hps_ecal_scalers_app));
   { hps_ecal_scalers_app *p; p=(hps_ecal_scalers_app*)0x1000; if (p) { }
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"hps_crate_map[2][22]=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,4,"hps_ecal_crate_slot_scalers[2][22][16]=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,4,"hps_ecal_crate_slot_ref[2][22]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_CrateMsgClient),-1,-1,4,"crate_hps[2]=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_TCanvas),-1,-1,4,"pTC=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_TH2I),-1,-1,4,"pH=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_TRootEmbeddedCanvas),-1,-1,4,"pCanvas=",0,(char*)NULL);
   G__memvar_setup((void*)0,105,0,0,-1,-1,-1,4,"hpsCrates[2]=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->doLogScale)-(long)(p)),103,0,0,-1,-1,-1,1,"doLogScale=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->updatePeriod)-(long)(p)),105,0,0,-1,-1,-1,1,"updatePeriod=",0,(char*)NULL);
   G__memvar_setup((void*)((long)(&p->scalerType)-(long)(p)),105,0,0,-1,-1,-1,1,"scalerType=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarhps_ecal_scalers_Dict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfunchps_ecal_scalers_app(void) {
   /* hps_ecal_scalers_app */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_hps_ecal_scalers_app));
   G__memfunc_setup("connect_to_server",1826,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("read_scalers",1256,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_ch",618,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 2, 1, 4, 0, 
"i - - 0 - x i - - 0 - y", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_crate_map",1355,(G__InterfaceMethod) NULL, 105, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("get_total_rate",1486,(G__InterfaceMethod) NULL, 117, G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_totalrates_t), -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("draw_scalers",1274,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("normalize_scalers",1821,(G__InterfaceMethod) NULL, 121, -1, -1, 0, 0, 1, 4, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("hps_ecal_scalers_app",2091,G__hps_ecal_scalers_Dict_772_0_8, 105, G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_hps_ecal_scalers_app), -1, 0, 3, 1, 1, 0, 
"U 'TGWindow' - 10 - p h - 'UInt_t' 0 - w "
"h - 'UInt_t' 0 - h", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DoExit",589,G__hps_ecal_scalers_Dict_772_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("button_Save",1162,G__hps_ecal_scalers_Dict_772_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("button_LogEnable",1636,G__hps_ecal_scalers_Dict_772_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("refresh_scalers",1595,G__hps_ecal_scalers_Dict_772_0_12, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__hps_ecal_scalers_Dict_772_0_13, 85, G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&hps_ecal_scalers_app::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__hps_ecal_scalers_Dict_772_0_14, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&hps_ecal_scalers_app::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__hps_ecal_scalers_Dict_772_0_15, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&hps_ecal_scalers_app::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__hps_ecal_scalers_Dict_772_0_16, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&hps_ecal_scalers_app::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__hps_ecal_scalers_DictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__hps_ecal_scalers_Dict_772_0_20, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__hps_ecal_scalers_Dict_772_0_21, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&hps_ecal_scalers_app::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__hps_ecal_scalers_Dict_772_0_22, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&hps_ecal_scalers_app::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__hps_ecal_scalers_Dict_772_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&hps_ecal_scalers_app::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__hps_ecal_scalers_Dict_772_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&hps_ecal_scalers_app::DeclFileLine) ), 0);
   // automatic destructor
   G__memfunc_setup("~hps_ecal_scalers_app", 2217, G__hps_ecal_scalers_Dict_772_0_25, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfunchps_ecal_scalers_Dict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {
}

static void G__cpp_setup_global8() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalhps_ecal_scalers_Dict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
  G__cpp_setup_global8();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funchps_ecal_scalers_Dict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__hps_ecal_scalers_DictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_TQObject = { "TQObject" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_TCanvas = { "TCanvas" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_TH2I = { "TH2I" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_TGObject = { "TGObject" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_TGWindow = { "TGWindow" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_TGFrame = { "TGFrame" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_TGCompositeFrame = { "TGCompositeFrame" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_TGMainFrame = { "TGMainFrame" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_TRootEmbeddedCanvas = { "TRootEmbeddedCanvas" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_CrateMsgClient = { "CrateMsgClient" , 99 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_totalrates_t = { "totalrates_t" , 115 , -1 };
G__linked_taginfo G__hps_ecal_scalers_DictLN_hps_ecal_scalers_app = { "hps_ecal_scalers_app" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtablehps_ecal_scalers_Dict() {
  G__hps_ecal_scalers_DictLN_TClass.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_TBuffer.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_TMemberInspector.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_TObject.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_TQObject.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_TCanvas.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_TH2I.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_TGObject.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_TGWindow.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_TGFrame.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_TGCompositeFrame.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_TGMainFrame.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_TRootEmbeddedCanvas.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_CrateMsgClient.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_totalrates_t.tagnum = -1 ;
  G__hps_ecal_scalers_DictLN_hps_ecal_scalers_app.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtablehps_ecal_scalers_Dict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_TClass);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_TObject);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_TQObject);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_TCanvas);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_TH2I);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_TGObject);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_TGWindow);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_TGFrame);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_TGCompositeFrame);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_TGMainFrame);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_TRootEmbeddedCanvas);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_CrateMsgClient);
   G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_totalrates_t);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__hps_ecal_scalers_DictLN_hps_ecal_scalers_app),sizeof(hps_ecal_scalers_app),-1,62464,(char*)NULL,G__setup_memvarhps_ecal_scalers_app,G__setup_memfunchps_ecal_scalers_app);
}
extern "C" void G__cpp_setuphps_ecal_scalers_Dict(void) {
  G__check_setup_version(30051515,"G__cpp_setuphps_ecal_scalers_Dict()");
  G__set_cpp_environmenthps_ecal_scalers_Dict();
  G__cpp_setup_tagtablehps_ecal_scalers_Dict();

  G__cpp_setup_inheritancehps_ecal_scalers_Dict();

  G__cpp_setup_typetablehps_ecal_scalers_Dict();

  G__cpp_setup_memvarhps_ecal_scalers_Dict();

  G__cpp_setup_memfunchps_ecal_scalers_Dict();
  G__cpp_setup_globalhps_ecal_scalers_Dict();
  G__cpp_setup_funchps_ecal_scalers_Dict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfunchps_ecal_scalers_Dict();
  return;
}
class G__cpp_setup_inithps_ecal_scalers_Dict {
  public:
    G__cpp_setup_inithps_ecal_scalers_Dict() { G__add_setup_func("hps_ecal_scalers_Dict",(G__incsetup)(&G__cpp_setuphps_ecal_scalers_Dict)); G__call_setup_funcs(); }
   ~G__cpp_setup_inithps_ecal_scalers_Dict() { G__remove_setup_func("hps_ecal_scalers_Dict"); }
};
G__cpp_setup_inithps_ecal_scalers_Dict G__cpp_setup_initializerhps_ecal_scalers_Dict;

