/********************************************************************
* hps_ecal_scalers_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error hps_ecal_scalers_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablehps_ecal_scalers_Dict();
extern void G__cpp_setup_inheritancehps_ecal_scalers_Dict();
extern void G__cpp_setup_typetablehps_ecal_scalers_Dict();
extern void G__cpp_setup_memvarhps_ecal_scalers_Dict();
extern void G__cpp_setup_globalhps_ecal_scalers_Dict();
extern void G__cpp_setup_memfunchps_ecal_scalers_Dict();
extern void G__cpp_setup_funchps_ecal_scalers_Dict();
extern void G__set_cpp_environmenthps_ecal_scalers_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "hps_ecal_scalers.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__hps_ecal_scalers_DictLN_TClass;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_TBuffer;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_TMemberInspector;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_TObject;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_TQObject;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_TCanvas;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_TH2I;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_TGObject;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_TGWindow;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_TGFrame;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_TGCompositeFrame;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_TGMainFrame;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_TRootEmbeddedCanvas;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_CrateMsgClient;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_totalrates_t;
extern G__linked_taginfo G__hps_ecal_scalers_DictLN_hps_ecal_scalers_app;

/* STUB derived class for protected member access */
